# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmeta',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FAILURE', 'FAILURE'), ('REVOKED', 'REVOKED'), ('SUCCESS', 'SUCCESS'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('STARTED', 'STARTED')], default='PENDING', max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='taskstate',
            name='state',
            field=models.CharField(db_index=True, max_length=64, verbose_name='state'),
        ),
    ]
